version: '3.9'

services:
  react-app:
    build: ./my-app
    restart: always
    ports:
      - "3000:3000"

  api:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: